<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>jpam</artifactId>
		<groupId>io.github.macster110</groupId>
		<version>1.0.0</version>
	</parent>

	<artifactId>jpambinaries</artifactId>
	<version>0.0.31</version>
	
	<description>Data parsing tools for passive acoustic monitoring and data processing.</description>

	<name>jpambinaries</name>
	<!-- Replace placeholder URL with project website/repo URL -->
	<url>https://github.com/macster110/jpam</url>

	<dependencies>
		
		<!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
		<dependency>
		    <groupId>org.junit.jupiter</groupId>
		    <artifactId>junit-jupiter-api</artifactId>
		    <version>5.8.2</version>
		    <scope>test</scope>
		</dependency>
		

		<!-- Useful utilities -->
		<dependency>
			<groupId>io.github.macster110</groupId>
			<artifactId>jpamutils</artifactId>
			<version>1.0.0</version>
		</dependency>

	</dependencies>

	<licenses>
		<license>
			<name>Apache-2.0</name>
			<url>https://opensource.org/licenses/apache-2.0</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<!-- Provide full SCM connections as required by Central Publishing -->
	<scm>
		<connection>scm:git:https://github.com/macster110/jpam.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/macster110/jpam.git</developerConnection>
		<url>https://github.com/macster110/jpam</url>
		<tag>HEAD</tag>
	</scm>
	<developers>
		<developer>
			<id>macster110</id>
			<name>Jamie Macaulay</name>
			<email>macster110@gmail.com</email>
			<roles>
				<role>Developer</role>
			</roles>
		</developer>
	</developers>


	<!--<distributionManagement>
		<repository>
			<id>bintray-macster110-jpam</id>
			<name>macster110-jpam</name>
			<url>https://api.bintray.com/maven/macster110/jpam/jpambinaries/;publish=1</url>
		</repository>
	</distributionManagement>-->

</project>